Creation modal to confirm user delete action
eduardopessoa89/Point-of-Sale pull request #60
Opened 2020-07-06 23:06 UTC by douglasemiliano

close #30

2020-07-08 19:52 UTC, douglasemiliano commented on angular/pos/src/app/components/user/user.service.ts
> +  userDeleted: number;
Coloquei UserDeletedID, acho que fica um nome mais claro

2020-07-08 19:53 UTC, douglasemiliano commented on angular/pos/src/app/components/user/user-list/user-list.component.ts
> +    this.userService.setUserDeleted(id);
Ta faltando uma linha ai na função que é justamente pra abir o modal.
  
openDeleteDialog(id: number){
    this.userService.setUserDeleted(id);
    this.dialog.open(ModalDeleteComponent);
  }

2020-07-09 17:39 UTC, douglasemiliano commented on angular/pos/src/app/components/user/user.service.ts
> +  userDeleted: number;
Realmente, na minha task nova precisei usar essa variável ai mudei pra UserID

2020-07-09 17:39 UTC, douglasemiliano commented on angular/pos/src/app/components/user/modal-delete/modal-delete.component.html
> +    <div class="col"><button type="button" class="btn btn-danger" (click) = "goToList()"> Não </button></div>
blz

2020-07-13 22:11 UTC, roberto-silva commented
Continua com conflitos

2020-07-13 22:15 UTC, roberto-silva requested changes

2020-07-13 22:15 UTC, roberto-silva commented on angular/pos/src/app/shared/shared.module.ts
> +>>>>>>> 85845f76450982ca50f37d0ced4ac7be71947481
Continua com conflitos

2020-07-13 22:15 UTC, roberto-silva commented on angular/pos/src/app/shared/shared.module.ts
> +>>>>>>> 85845f76450982ca50f37d0ced4ac7be71947481
Continua com conflitos

2020-07-14 14:23 UTC, roberto-silva submitted a review, later dismissed

2020-07-14 14:25 UTC, roberto-silva requested changes
A mensagem ficou muito pequena, tanto no sentido da frase quanto no modal.
Tira a titulo de confirmar a mensagem de baixo já expressa a ideia de confirmação.

2021-05-22 12:52 UTC, closed without merging